apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: jefk13/person-service
          ports:
            - containerPort: 8083
          env:
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_HOST
              value: mongo-people
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
spec:
  ports:
    - port: 8083
  selector:
    app: person-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: jefk13/ticket-service
          ports:
            - containerPort: 8082
          env:
            - name: PERSON_SERVICE_BASEURL
              value: person-service:8083
            - name: MYSQL_DB_USERNAME
              value: root
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_HOST
              value: mysql-tickets
            - name: MYSQL_DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  ports:
    - port: 8082
  selector:
    app: ticket-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      containers:
        - name: ride-service
          image: jefk13/ride-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_HOST
              value: mongo-rides
---
apiVersion: v1
kind: Service
metadata:
  name: ride-service
spec:
  ports:
    - port: 8080
  selector:
    app: ride-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: jefk13/event-service
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_DB_USERNAME
              value: root
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_HOST
              value: mysql-events
            - name: MYSQL_DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  ports:
    - port: 8081
  selector:
    app: event-service