services:
  mongo-people:
    image: mongo:latest
    container_name: mongo-people
    volumes:
      - mongodb_person_data:/data/db

  mongo-rides:
    image: mongo:latest
    container_name: mongo-rides
    volumes:
      - mongodb_ride_data:/data/db
    
  mysql-tickets:
    image: mysql:latest
    container_name: mysql-tickets
    volumes:
      - mysql_ticket_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    
  mysql-events:
    image: mysql:latest
    container_name: mysql-events
    volumes:
      - mysql_event_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    
  person-service:
    depends_on:
      - mongo-people
    image: jefk13/person-service
    container_name: person-service
    restart: on-failure
    links:
      - mongo-people
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-people
   
  ticket-service:
    depends_on:
      - mysql-tickets
      - person-service
    image: jefk13/ticket-service
    container_name: ticket-service
    restart: on-failure
    links:
      - mysql-tickets
    environment:
      PERSON_SERVICE_BASEURL: person-service:8083
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-tickets
      MYSQL_DB_PORT: 3306

  ride-service:
    depends_on:
      - mongo-rides
    image: jefk13/ride-service
    container_name: ride-service
    restart: on-failure
    links:
      - mongo-rides
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-rides

  event-service:
    depends_on:
      - mysql-events
    image: jefk13/event-service
    container_name: event-service
    restart: on-failure
    links:
      - mysql-events
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-events
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - person-service
      - ticket-service
      - ride-service
      - event-service
    image: jefk13/api-gateway
    container_name: api-gateway
    ports:
      - 8084:8084
    links:
      - person-service
      - ticket-service
      - ride-service
      - event-service
    environment:
      PERSON_SERVICE_BASEURL: person-service:8083
      TICKET_SERVICE_BASEURL: ticket-service:8082
      EVENT_SERVICE_BASEURL: event-service:8081
      RIDE_SERVICE_BASEURL: ride-service:8080

  frontend:
    depends_on:
      - api-gateway
    image: jefk13/frontend
    container_name: frontend
    ports:
      - 8085:8085
    environment:
      API_GATEWAY_URL: api-gateway:8084

volumes:
  mongodb_person_data:
  mysql_ticket_data:
  mongodb_ride_data:
  mysql_event_data:
