services:
 mongo-people:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_person_data:/data/db

mongo-rides:
  image: mongo:latest
  ports:
    - 27018:27017
  volumes:
    - mongodb_ride_data:/data/db
    
 mysql-tickets:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_ticket_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-events:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_event_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 person-service:
  depends_on:
    - mongo-people
  image: jefk13/person-service
  ports:
    - 8083:8083
  links:
    - mongo-people
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-people
   
 ticket-service:
  depends_on:
    - mysql-ticket
    - person-service
  image: jefk13/ticket-service
  ports:
    - 8082:8082
  links:
    - mysql-tickets
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-tickets
   MYSQL_DB_PORT: 3306

 ride-service:
  depends_on:
    - mongo-rides
  image: jefk13/ride-service
  ports:
    - 8080:8080
  links:
    - mongo-rides
  environment:
   PERSON_SERVICE_BASEURL: person-service:8083
   MONGODB_PORT: 27018
   MONGODB_HOST: mongo-rides

event-service:
  depends_on:
    - mongo-events
  image: jefk13/event-service
  ports:
    - 8081:8081
  links:
    - mongo-events
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-events
   MYSQL_DB_PORT: 3307

 api-gateway:
   depends_on:
     - person-service
     - ticket-service
     - ride-service
     - event-service
   image: jefk13/api-gateway
   ports:
     - 8084:8084
   links:
     - person-service
     - ticket-service
     - ride-service
     - event-service
   environment:
     PERSON_SERVICE_BASEURL: product-service:8083
     TICKET_SERVICE_BASEURL: order-service:8082
     EVENT_SERVICE_BASEURL: event-service:8081
     RIDE_SERVICE_BASEURL: ride-service:8080

volumes:
 mongodb_person_data:
 mongodb_ticket_data:
 mysql_ride_data:
 mysql_event_data:
