apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    path: /metrics
  selector:
    matchLabels:
      app: event-service
  namespaceSelector:
    matchNames:
      - default