apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-tickets
  template:
    metadata:
      labels:
        app: mysql-tickets
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-ticket-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-tickets
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-tickets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-events
  template:
    metadata:
      labels:
        app: mysql-events
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-event-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-events
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-events